version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: cinedata-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    container_name: cinedata-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
      MYSQL_USER: movieuser
      MYSQL_PASSWORD: moviepass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  movies:
    build: ./movieService
    container_name: cinedata-movies
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: movies_db
      DB_PORT: 3306
    restart: always

  users:
    build: ./userService
    container_name: cinedata-users
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    restart: always

  frontend:
    build: ./frontend
    container_name: cinedata-frontend
    ports:
      - "5173:80"
    depends_on:
      - users
      - movies
    restart: always

volumes:
  mongo_data:
  mysql_data:
